name: Expo EAS Build - Android Preview

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Fix Expo dependencies + FORCE gesture-handler 2.30.0
        run: |
          npx expo install --fix
          npx expo install react-native-gesture-handler
          npm install react-native-gesture-handler@~2.30.0 --save-exact   # <-- TO JE KLJUČNO ZA CI

      - name: Clean cache (pomembno za local build)
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force
          npm install

      - name: Run Expo Doctor
        run: npx expo-doctor

      - name: Build Android Preview (local)
        run: |
          eas build --platform android --profile preview --local --non-interactive --output=./build-result.apk --clear-cache
